#!/usr/bin/env python3
"""From rooms.yaml, emit: an Ingress with one host per entry in `ports` (marvin-<port>.<domain> -> apps proxy),
and a ConfigMap telling the worker which ports have a hostname.

Usage: gen_apps.py deploy/k8s/rooms.yaml > deploy/k8s/apps.yaml

`domain` and `ingress_class` come from rooms.yaml (defaults: marvin.example.com's parent, i.e. example.com, and nginx).
Add DNS records for `marvin-<port>.<domain>` yourself, or let external-dns do it from the Ingress hosts."""
import sys

import yaml

DEFAULT_DOMAIN = "example.com"
DEFAULT_INGRESS_CLASS = "nginx"


def annotations(ui_host: str) -> dict:
    return {
        "nginx.ingress.kubernetes.io/proxy-read-timeout": "3600",  # dev servers use websockets for hot reload
        "nginx.ingress.kubernetes.io/proxy-send-timeout": "3600",
        "nginx.ingress.kubernetes.io/proxy-body-size": "50m",
        # Ingress controllers often add "X-Frame-Options: DENY" + "frame-ancestors 'self'" globally; the room embeds app
        # previews, so allow framing from the Marvin host only. (headers-more directives at location level replace the inherited set.)
        "nginx.ingress.kubernetes.io/configuration-snippet": (
            f"more_set_headers \"Content-Security-Policy: frame-ancestors 'self' https://{ui_host}\";\n"
        ),
    }


def main(path: str) -> None:
    data = yaml.safe_load(open(path)) or {}
    domain = str(data.get("domain") or DEFAULT_DOMAIN)
    ui_host = str(data.get("ui_host") or f"marvin.{domain}")
    ingress_class = str(data.get("ingress_class") or DEFAULT_INGRESS_CLASS)
    ports = sorted({int(p) for p in data.get("ports", [])})
    rules = [{"host": f"marvin-{p}.{domain}", "http": {"paths": [{"path": "/", "pathType": "Prefix", "backend": {"service": {"name": "marvin-apps", "port": {"number": 8081}}}}]}} for p in ports]
    docs = [
        {"apiVersion": "v1", "kind": "ConfigMap", "metadata": {"name": "marvin-apps-env"},
         "data": {"MARVIN_APPS_DOMAIN": domain, "MARVIN_APPS_PREFIX": "marvin-", "MARVIN_APPS_PORTS": ",".join(str(p) for p in ports)}},
    ]
    if rules:
        docs.append({"apiVersion": "networking.k8s.io/v1", "kind": "Ingress", "metadata": {"name": "marvin-apps", "annotations": annotations(ui_host)},
                     "spec": {"ingressClassName": ingress_class, "rules": rules}})
    print("# generated by deploy/gen_apps.py from", path, "- do not edit")
    print(yaml.safe_dump_all(docs, sort_keys=False))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "deploy/k8s/rooms.yaml")
